[tool.fletpack]
app_name = "Essa Fera Bicho"
package_name = "com.exemplo.essaferabicho"
description = "Um app para ver rapidamente o saldo de crypto"
version = "1.3.2"
screen_orientation = "portrait"
dpi = 551
meta_viewport = "width=device-width, initial-scale=0.9, maximum-scale=0.9, user-scalable=no"